version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
#    image: registry.heroku.com/ancient-temple-48054/web:latest
    image: docker.pkg.github.com/yayunl/moviecatalog/web:latest