version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: /usr/src/start
#    command: tail -f /dev/null
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.dev
    depends_on:
      - db


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.dev


  dbAdmin:
    image: dpage/pgadmin4
    env_file:
      - ./envs/.env.dev
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin:
