version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.dev